using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tabuadas
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("-------------");
            Console.WriteLine("Tabuada do 3");
            Console.WriteLine("-------------");
            Console.WriteLine("3 x 1 = " + (3*1));
            Console.WriteLine("3 x 2 = " + (3*2));
            Console.WriteLine("3 x 3 = " + (3*3));
            Console.WriteLine("3 x 4 = " + (3*4));
            Console.WriteLine("3 x 5 = " + (3*5));
            Console.WriteLine("3 x 6 = " + (3*6));
            Console.WriteLine("3 x 7 = " + (3*7));
            Console.WriteLine("3 x 8 = " + (3*8));
            Console.WriteLine("3 x 9 = " + (3*9));
            Console.WriteLine("3 x 10 = " + (3*10));
            Console.WriteLine("-------------");
            Console.WriteLine("Tabuada do 4");
            Console.WriteLine("-------------");
            Console.WriteLine("4 x 1 = " + (4 * 1));
            Console.WriteLine("4 x 2 = " + (4 * 2));
            Console.WriteLine("4 x 3 = " + (4 * 3));
            Console.WriteLine("4 x 4 = " + (4 * 4));
            Console.WriteLine("4 x 5 = " + (4 * 5));
            Console.WriteLine("4 x 6 = " + (4 * 6));
            Console.WriteLine("4 x 7 = " + (4 * 7));
            Console.WriteLine("4 x 8 = " + (4 * 8));
            Console.WriteLine("4 x 9 = " + (4 * 9));
            Console.WriteLine("4 x 10 = " + (4 * 10));
            Console.WriteLine("-------------");
            Console.WriteLine("Tabuada do 5");
            Console.WriteLine("-------------");
            Console.WriteLine("5 x 1 = " + (5 * 1));
            Console.WriteLine("5 x 2 = " + (5 * 2));
            Console.WriteLine("5 x 3 = " + (5 * 3));
            Console.WriteLine("5 x 4 = " + (5 * 4));
            Console.WriteLine("5 x 5 = " + (5 * 5));
            Console.WriteLine("5 x 6 = " + (5 * 6));
            Console.WriteLine("5 x 7 = " + (5 * 7));
            Console.WriteLine("5 x 8 = " + (5 * 8));
            Console.WriteLine("5 x 9 = " + (5 * 9));
            Console.WriteLine("5 x 10 = " + (5 * 10));
            Console.WriteLine("-------------");
            Console.WriteLine("Tabuada do 6");
            Console.WriteLine("-------------");
            Console.WriteLine("6 x 1 = " + (6 * 1));
            Console.WriteLine("6 x 2 = " + (6 * 2));
            Console.WriteLine("6 x 3 = " + (6 * 3));
            Console.WriteLine("6 x 4 = " + (6 * 4));
            Console.WriteLine("6 x 5 = " + (6 * 5));
            Console.WriteLine("6 x 6 = " + (6 * 6));
            Console.WriteLine("6 x 7 = " + (6 * 7));
            Console.WriteLine("6 x 8 = " + (6 * 8));
            Console.WriteLine("6 x 9 = " + (6 * 9));
            Console.WriteLine("6 x 10 = " + (6 * 10));
            Console.WriteLine("-------------");
            Console.WriteLine("Tabuada do 7");
            Console.WriteLine("-------------");
            Console.WriteLine("7 x 1 = " + (7 * 1));
            Console.WriteLine("7 x 2 = " + (7 * 2));
            Console.WriteLine("7 x 3 = " + (7 * 3));
            Console.WriteLine("7 x 4 = " + (7 * 4));
            Console.WriteLine("7 x 5 = " + (7 * 5));
            Console.WriteLine("7 x 6 = " + (7 * 6));
            Console.WriteLine("7 x 7 = " + (7 * 7));
            Console.WriteLine("7 x 8 = " + (7 * 8));
            Console.WriteLine("7 x 9 = " + (7 * 9));
            Console.WriteLine("7 x 10 = " + (7 * 10));
            Console.WriteLine("-------------");
            Console.WriteLine("Tabuada do 8");
            Console.WriteLine("-------------");
            Console.WriteLine("8 x 1 = " + (8 * 1));
            Console.WriteLine("8 x 2 = " + (8 * 2));
            Console.WriteLine("8 x 3 = " + (8 * 3));
            Console.WriteLine("8 x 4 = " + (8 * 4));
            Console.WriteLine("8 x 5 = " + (8 * 5));
            Console.WriteLine("8 x 6 = " + (8 * 6));
            Console.WriteLine("8 x 7 = " + (8 * 7));
            Console.WriteLine("8 x 8 = " + (8 * 8));
            Console.WriteLine("8 x 9 = " + (8 * 9));
            Console.WriteLine("8 x 10 = " + (8 * 10));
            Console.WriteLine("-------------");
            Console.WriteLine("Tabuada do 9");
            Console.WriteLine("-------------");
            Console.WriteLine("9 x 1 = " + (9 * 1));
            Console.WriteLine("9 x 2 = " + (9 * 2));
            Console.WriteLine("9 x 3 = " + (9 * 3));
            Console.WriteLine("9 x 4 = " + (9 * 4));
            Console.WriteLine("9 x 5 = " + (9 * 5));
            Console.WriteLine("9 x 6 = " + (9 * 6));
            Console.WriteLine("9 x 7 = " + (9 * 7));
            Console.WriteLine("9 x 8 = " + (9 * 8));
            Console.WriteLine("9 x 9 = " + (9 * 9));
            Console.WriteLine("9 x 10 = " + (9 * 10));
            Console.WriteLine("-------------");
            Console.WriteLine("Tabuada do 10");
            Console.WriteLine("-------------");
            Console.WriteLine("10 x 1 = " + (10 * 1));
            Console.WriteLine("10 x 2 = " + (10 * 2));
            Console.WriteLine("10 x 3 = " + (10 * 3));
            Console.WriteLine("10 x 4 = " + (10 * 4));
            Console.WriteLine("10 x 5 = " + (10 * 5));
            Console.WriteLine("10 x 6 = " + (10 * 6));
            Console.WriteLine("10 x 7 = " + (10 * 7));
            Console.WriteLine("10 x 8 = " + (10 * 8));
            Console.WriteLine("10 x 9 = " + (10 * 9));
            Console.WriteLine("10 x 10 = " + (10 * 10));
            Console.ReadLine();

        }
    }
}
